### ISSUE TITLE
You have a problem

### ISSUE THREAD

**Issue by ColinChiu87** [ChingHuiHui/hui-website#1]
![7F6017C6-6312-4446-8282-691B8F2B4275](https://user-images.githubusercontent.com/50079003/114122258-7cffaa80-9922-11eb-8ee0-c1f3eaec1863.png)

**Comment by ColinChiu87** [comment]
https://user-images.githubusercontent.com/50079003/114122666-59892f80-9923-11eb-98f8-b530063b8786.MP4

**Comment by ChingHuiHui** [comment]
>  IMG_3797.MP4

fix !

**Comment by ChingHuiHui** [comment]
**fix !**
